const BANK=window.RPAS_QUESTION_BANK||[],$=s=>document.querySelector(s),letters=['A','B','C','D'];
let state={mode:'study',questions:[],index:0,answers:{},flags:new Set(),remaining:0,timer:null,submitted:false};
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function prep(q,shuffleAnswers=true){let x=JSON.parse(JSON.stringify(q));if(shuffleAnswers){let p=x.options.map((v,i)=>({v,ok:i===x.answer}));shuffle(p);x.options=p.map(o=>o.v);x.answer=p.findIndex(o=>o.ok)}return x}
function fmt(t){let m=Math.floor(t/60),s=t%60;return `${m}:${String(s).padStart(2,'0')}`}
function init(){[...new Set(BANK.map(q=>q.category))].forEach(c=>{let o=document.createElement('option');o.value=c;o.textContent=`${c} (${BANK.filter(q=>q.category===c).length})`;$('#studyCategory').appendChild(o)});$('#studyStart').onclick=()=>start('study');$('#examStart').onclick=()=>start('exam');$('#nextBtn').onclick=()=>go(state.index+1);$('#prevBtn').onclick=()=>go(state.index-1);$('#flagBtn').onclick=toggleFlag;$('#endBtn').onclick=()=>{if(confirm('End this session and view results?'))finish()};$('#submitBtn').onclick=()=>{if(confirm('Submit this session now?'))finish()};document.addEventListener('keydown',keys)}
function start(mode,custom){clearInterval(state.timer);let qs;if(custom){qs=custom.map(q=>prep(q,true))}else if(mode==='exam'){qs=shuffle([...BANK]).slice(0,50).map(q=>prep(q,$('#examShuffle').checked))}else{let pool=$('#studyCategory').value==='All'?[...BANK]:BANK.filter(q=>q.category===$('#studyCategory').value);if($('#studyShuffle').checked)shuffle(pool);let n=$('#studyCount').value==='all'?pool.length:Math.min(Number($('#studyCount').value),pool.length);qs=pool.slice(0,n).map(q=>prep(q,$('#studyShuffle').checked))}state={mode,questions:qs,index:0,answers:{},flags:new Set(),remaining:mode==='exam'?3600:0,timer:null,submitted:false};$('#home').classList.add('hidden');$('#results').classList.add('hidden');$('#quiz').classList.remove('hidden');$('#topStats').classList.remove('hidden');if(mode==='exam'){tick();state.timer=setInterval(tick,1000)}else $('#timerPill').textContent='Study';buildNav();render();window.scrollTo({top:0})}
function tick(){$('#timerPill').textContent=fmt(state.remaining);$('#timerPill').classList.toggle('danger',state.remaining<=300);if(state.remaining<=0){finish();return}state.remaining--}
function buildNav(){let g=$('#navGrid');g.innerHTML='';state.questions.forEach((q,i)=>{let b=document.createElement('button');b.className='navq';b.textContent=i+1;b.title=`Question ${i+1}: ${q.category}`;b.onclick=()=>go(i);g.appendChild(b)});updateNav()}
function updateNav(){[...document.querySelectorAll('.navq')].forEach((b,i)=>{b.classList.toggle('current',i===state.index);b.classList.toggle('answered',state.answers[i]!==undefined);b.classList.toggle('flagged',state.flags.has(i))});$('#progressPill').textContent=`${state.index+1} / ${state.questions.length}`;let c=Object.entries(state.answers).filter(([i,a])=>state.questions[Number(i)].answer===a).length;$('#scorePill').textContent=state.mode==='study'?`Score ${c}/${Object.keys(state.answers).length}`:`Answered ${Object.keys(state.answers).length}`}
function render(){let q=state.questions[state.index],chosen=state.answers[state.index];$('#categoryTag').textContent=q.category;$('#questionNumber').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('#questionText').textContent=q.question;$('#flagBtn').textContent=state.flags.has(state.index)?'★ Flagged':'☆ Flag';let vb=$('#visualBox');if(q.visual){vb.innerHTML=q.visual;vb.classList.remove('hidden')}else{vb.innerHTML='';vb.classList.add('hidden')}let opts=$('#options');opts.innerHTML='';q.options.forEach((text,i)=>{let b=document.createElement('button');b.className='option';b.innerHTML=`<span class="letter">${letters[i]}</span><span>${escapeHtml(text)}</span>`;if(chosen!==undefined)b.classList.add('selected');if(state.mode==='study'&&chosen!==undefined){b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===chosen&&chosen!==q.answer)b.classList.add('wrong')}b.onclick=()=>select(i);opts.appendChild(b)});let list=$('#sourceList');list.innerHTML='';q.sources.forEach(s=>{let li=document.createElement('li');li.innerHTML=`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${escapeHtml(s.label)}</a><span class="refkind">${escapeHtml(s.kind)}</span>`;list.appendChild(li)});$('#sourceNote').textContent=q.sourceNote;let hide=state.mode==='exam'&&$('#hideRefsExam').checked&&!state.submitted;$('#sourceBox').classList.toggle('hidden',hide);let fb=$('#feedback');if(state.mode==='study'&&chosen!==undefined){let ok=chosen===q.answer;fb.className='feedback show '+(ok?'good':'bad');$('#feedbackTitle').textContent=ok?'Correct':'Incorrect';$('#feedbackBody').textContent=q.explanation}else fb.className='feedback';$('#nextBtn').textContent=state.index===state.questions.length-1?'Finish':'Next →';updateNav()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function select(i){if(state.mode==='study'&&state.answers[state.index]!==undefined)return;state.answers[state.index]=i;render();if(state.mode==='exam')setTimeout(()=>{if(state.index<state.questions.length-1)go(state.index+1)},180)}
function go(i){if(i<0)return;if(i>=state.questions.length){finish();return}state.index=i;render();document.querySelector('#questionCard').scrollIntoView({behavior:'smooth',block:'start'})}
function toggleFlag(){state.flags.has(state.index)?state.flags.delete(state.index):state.flags.add(state.index);render()}
function keys(e){if($('#quiz').classList.contains('hidden'))return;if(['1','2','3','4'].includes(e.key))select(Number(e.key)-1);else if(e.key.toLowerCase()==='f')toggleFlag();else if(e.key==='ArrowRight')go(state.index+1);else if(e.key==='ArrowLeft')go(state.index-1)}
function finish(){clearInterval(state.timer);state.submitted=true;let total=state.questions.length,answered=Object.keys(state.answers).length,correct=0,stats={};state.questions.forEach((q,i)=>{let ok=state.answers[i]===q.answer;if(ok)correct++;stats[q.category]??={c:0,t:0};stats[q.category].t++;if(ok)stats[q.category].c++});let pct=Math.round(correct/total*100),pass=pct>=80;$('#quiz').classList.add('hidden');$('#topStats').classList.add('hidden');let r=$('#results');r.classList.remove('hidden');let rows=Object.entries(stats).map(([c,v])=>`<div class="catrow"><span>${escapeHtml(c)}</span><strong>${v.c}/${v.t} · ${Math.round(v.c/v.t*100)}%</strong></div>`).join('');let missed=state.questions.map((q,i)=>({q,i,chosen:state.answers[i]})).filter(x=>x.chosen!==x.q.answer);let review=missed.slice(0,100).map(x=>`<article class="reviewitem"><h4>${x.i+1}. ${escapeHtml(x.q.question)}</h4><div class="answerline">Your answer: <strong>${x.chosen===undefined?'Not answered':escapeHtml(x.q.options[x.chosen])}</strong></div><div class="answerline">Correct answer: <strong>${escapeHtml(x.q.options[x.q.answer])}</strong></div><p>${escapeHtml(x.q.explanation)}</p><div>${x.q.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${escapeHtml(s.label)}</a>`).join(' · ')}</div></article>`).join('');r.innerHTML=`<span class="badge">SESSION RESULTS</span><h1 class="${pass?'pass':'fail'}">${pass?'Pass standard reached':'Below the 80% standard'}</h1><div class="score">${pct}%</div><p><strong>${correct}/${total}</strong> correct · ${answered}/${total} answered · ${state.flags.size} flagged</p><h2>Knowledge-area performance</h2><div class="catrows">${rows}</div><div class="actions"><button class="secondary" id="homeBtn">Return home</button><button class="primary" id="retryBtn" ${missed.length?'':'disabled'}>Retry incorrect (${missed.length})</button></div><h2>Review</h2><div class="reviewlist">${review||'<p>No incorrect answers.</p>'}</div>`;$('#homeBtn').onclick=home;$('#retryBtn').onclick=()=>start('study',missed.map(x=>x.q));window.scrollTo({top:0,behavior:'smooth'})}
function home(){clearInterval(state.timer);$('#results').classList.add('hidden');$('#quiz').classList.add('hidden');$('#home').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
init();
